language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .

script:
  coverage run --source=fmap nosetests

after_success:
  coveralls